apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - mysql-statefulset.yaml
  - redis-deployment.yaml
  - nacos-deployment.yaml
  - rocketmq-deployment.yaml
