apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketmq-namesrv
  namespace: canteen-infra
  labels:
    app: rocketmq-namesrv
    tier: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocketmq-namesrv
  template:
    metadata:
      labels:
        app: rocketmq-namesrv
        tier: infra
    spec:
      containers:
        - name: namesrv
          image: apache/rocketmq:5.1.4
          ports:
            - containerPort: 9876
          command: ["sh", "mqnamesrv"]
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          readinessProbe:
            tcpSocket:
              port: 9876
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: rocketmq-namesrv
  namespace: canteen-infra
spec:
  selector:
    app: rocketmq-namesrv
  ports:
    - port: 9876
      targetPort: 9876
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketmq-broker
  namespace: canteen-infra
  labels:
    app: rocketmq-broker
    tier: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocketmq-broker
  template:
    metadata:
      labels:
        app: rocketmq-broker
        tier: infra
    spec:
      containers:
        - name: broker
          image: apache/rocketmq:5.1.4
          ports:
            - containerPort: 10911
          command: ["sh", "mqbroker", "-n", "rocketmq-namesrv:9876"]
          env:
            - name: NAMESRV_ADDR
              value: "rocketmq-namesrv.canteen-infra:9876"
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          readinessProbe:
            tcpSocket:
              port: 10911
            initialDelaySeconds: 15
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: rocketmq-broker
  namespace: canteen-infra
spec:
  selector:
    app: rocketmq-broker
  ports:
    - port: 10911
      targetPort: 10911
